### ISSUE TITLE
无法收集contianerd运行时日志内容到kafka

### ISSUE THREAD

**Issue by shboui** [w8t-io/WatchLog#9]
k8s版本：1.24
containerd版本：containerd github.com/containerd/containerd 1.7.11 64b8a811b07ba6288238eefc14d898ee0b5b99ba
yaml内容：
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: watch-log
  name: watch-log
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: watch-log
  template:
    metadata:
      labels:
        app: watch-log
    spec:
      containers:
        - env:
            - name: "RUNTIME_TYPE"
              value: "containerd"
            - name: "LOGGING_OUTPUT"
              value: "kafka"
            - name: "KAFKA_BROKERS"
              value: "10.10.10.10:9092"
            - name: "PILOT_LOG_PREFIX" # 设置日志配置前缀
              value: "parse" # 可以配置多个
            - name: "NODE_NAME"
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: cairry/watchlog:20240529
          imagePullPolicy: Always
          name: watch-log
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /var/run/containerd/containerd.sock
              name: containersock
            - mountPath: /var/run/docker.sock
              name: sock
            - mountPath: /host
              name: root
              readOnly: true
            - mountPath: /var/lib/filebeat
              name: varlib
            - mountPath: /var/log/filebeat
              name: varlog
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - hostPath:
            path: /run/containerd/containerd.sock
            type: ""
          name: containersock
        - hostPath:
            path: /var/run/docker.sock
            type: ""
          name: sock
        - hostPath:
            path: /
            type: ""
          name: root
        - hostPath:
            path: /var/lib/filebeat
            type: DirectoryOrCreate
          name: varlib
        - hostPath:
            path: /var/log/filebeat
            type: DirectoryOrCreate
          name: varlog
```

报错内容
```
time="2024-07-25T12:32:04Z" level=error msg="filebeat watcher scan error: failed to get registry state: EOF"
time="2024-07-25T12:32:42Z" level=debug msg="Process container destroy event: f0f443301f06c055faa8a859686c499c1c80555ec304654afa77cbc75d681bd0"
time="2024-07-25T12:32:42Z" level=info msg="Try removing log config f0f443301f06c055faa8a859686c499c1c80555ec304654afa77cbc75d681bd0"
time="2024-07-25T12:32:42Z" level=warning msg="removing f0f443301f06c055faa8a859686c499c1c80555ec304654afa77cbc75d681bd0 log config failure"
time="2024-07-25T12:32:42Z" level=error msg="Process container destroy event error: f0f443301f06c055faa8a859686c499c1c80555ec304654afa77cbc75d681bd0, remove /usr/share/filebeat/inputs.d/f0f443301f06c055faa8a859686c499c1c80555ec304654afa77cbc75d681bd0.yml: no such file or directory"
time="2024-07-25T12:32:42Z" level=debug msg="Process container destroy event: 67e786f49e218bf452ad2e1a1290788c0f1444361805b481a4253dbafedf417f"
time="2024-07-25T12:32:42Z" level=info msg="Try removing log config 67e786f49e218bf452ad2e1a1290788c0f1444361805b481a4253dbafedf417f"
time="2024-07-25T12:32:42Z" level=warning msg="removing 67e786f49e218bf452ad2e1a1290788c0f1444361805b481a4253dbafedf417f log config failure"
time="2024-07-25T12:32:42Z" level=error msg="Process container destroy event error: 67e786f49e218bf452ad2e1a1290788c0f1444361805b481a4253dbafedf417f, remove /usr/share/filebeat/inputs.d/67e786f49e218bf452ad2e1a1290788c0f1444361805b481a4253dbafedf417f.yml: no such file or directory"
time="2024-07-25T12:32:43Z" level=debug msg="Process container destroy event: 7a17c223f92750eb912d41c295b476576076a63b8bb2e50b4e09efe949e9d69f"
time="2024-07-25T12:32:43Z" level=info msg="Try removing log config 7a17c223f92750eb912d41c295b476576076a63b8bb2e50b4e09efe949e9d69f"
time="2024-07-25T12:32:43Z" level=warning msg="removing 7a17c223f92750eb912d41c295b476576076a63b8bb2e50b4e09efe949e9d69f log config failure"
time="2024-07-25T12:32:43Z" level=error msg="Process container destroy event error: 7a17c223f92750eb912d41c295b476576076a63b8bb2e50b4e09efe949e9d69f, remove /usr/share/filebeat/inputs.d/7a17c223f92750eb912d41c295b476576076a63b8bb2e50b4e09efe949e9d69f.yml: no such file or directory"
time="2024-07-25T12:33:04Z" level=error msg="filebeat watcher scan error: failed to get registry state: EOF"
time="2024-07-25T12:34:04Z" level=error msg="filebeat watcher scan error: failed to get registry state: EOF"
time="2024-07-25T12:35:04Z" level=error msg="filebeat watcher scan error: failed to get registry state: EOF"
time="2024-07-25T12:36:04Z" level=error msg="filebeat watcher scan error: failed to get registry state: EOF"
```
